version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - healthdata

  healthdata2mqtt:
    build: .
    container_name: healthdata2mqtt
    restart: unless-stopped
    privileged: true
    network_mode: host
    volumes:
      - ./user:/app/user
      - /var/run/dbus:/var/run/dbus:ro
    environment:
      - MQTT_HOST=localhost
      - MQTT_PORT=1883
    depends_on:
      - mosquitto
    devices:
      - /dev/bus/usb:/dev/bus/usb

  health-api:
    build: ./mqtt-listener
    container_name: health-data-api
    restart: unless-stopped
    ports:
      - "5001:5001"
    environment:
      - MQTT_HOST=mosquitto
      - MQTT_PORT=1883
      - MQTT_USERNAME=${MQTT_USERNAME:-}
      - MQTT_PASSWORD=${MQTT_PASSWORD:-}
    depends_on:
      - mosquitto
    networks:
      - healthdata

networks:
  healthdata:
    driver: bridge